---
title: "補充 - 變數型態"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 向量(vector)

```{r}
x = c(1, 3, 5, 7, 9)  # 建立向量，或聯結不同的向量
is.vector(x)  # 查詢x是否為向量變數
y = c(2, "stat", T)  # 元素屬性需相同
x[1]; y[-2]  # 向量指標
x[c(1, 3, 5)] = c(2, 4, 6)
c(x, y[1])
length(x)  # 算出元素個數
names(x)  # 查詢或建立向量的元素名稱
names(x) = c("a", "b", "c", "d", "e")
x[c(3, 5)]; x[c("c", "e")]
```

## 陣列(array), 矩陣(matrix)

```{r}
X = array(1:6, c(3, 2))  # matrix(1:6, 3, 2) # 建立陣列變數
Y = array(1:12, c(2, 3, 2))
is.array(X); is.matrix(X)  # 查詢X是否為陣列及矩陣變數
rbind(x, x); cbind(x, x)  # 使用rbind及cbind來建立array變數
nrow(X)  # 查詢陣列的列數
ncol(X)  # 查詢陣列的行數
dim(Y)  # 查詢Y陣列的維度
rownames(X) = c("R1", "R2", "R3")
colnames(X) = c("C1", "C2")
```

- 矩陣(matrix)是陣列(array)的一個特例，一個二維的陣列就是矩陣。

```{r}
X = matrix(1:6, 3, 2)
Y = t(X)  # 轉置
Z = X %*% Y  # 矩陣相乘
diag(Z)  # 對角線函數
det(Z)  # 行列式
A = matrix(1:4, 2, 2)
b = c(2,2)
solve(A)  # 反矩陣
solve(A, b)  # 線性聯立方程式
eigen(Z)  # 特徵值與特徵向量
```

## 因子(Factor)

```{r}
x = c(1, 1, 1, 2, 2, 2)
y = factor(x)  # 等同於 as.factor(x)
y - 1
levels(y)  # 查詢或設定分類資料
levels(y) = c("一", "二")
nlevels(y)  # 查詢分類數目
```

- 請小心不要把因子變數型態的資料拿來進行數學運算。

## 串列(List)

```{r}
l = list(L1 = x, L2 = y, L3 = Z)
names(l)
l$L1  # 等同於 l[[1]] 或 l[["L1"]]
l[2]  # 等同於 l["L2"]
l$L3[1, 2]
l$L4 = 1:5
c(l, list(L5 = 1:10))
```

- 串列(list)的每個元素可以為不同的資料屬性，也可以具有不同長度，是相當實用的一種變數型態。
- 串列的指標系統較為特別，使用時要特別注意資料取出後的型態。

## 資料框架(Data-Frame)

```{r}
D = as.data.frame(Z)  # 將變數類型轉為data-frame
D[, 4] = c(T, F, T)
names(D) = c("D1", "D2", "D3", "D4")
```

- 資料框架(data frame)是串列(list)的一個特例，資料框架的每一個直行，就是串列中的一個元素。唯獨限制資料框架的每個元素(行)長度必須相同。
